# 李沐《动手学深度学习》原笔记整理：PyTorch 基础与自动求导

本笔记严格围绕原始学习范围整理：

1. Tensor 的形状、运算、拼接、广播和内存；
2. 表格数据的缺失值处理、独热编码和 Tensor 转换；
3. 标量、向量、矩阵、`axis/keepdims`、矩阵乘法和范数；
4. 计算图、链式法则、梯度累加、`detach` 和动态计算图。

原内容只合并重复部分，并增加必要的直观解释。模型训练、`DataLoader`、`nn.Module` 和 MLP 已移到 `deep_learning_extensions.ipynb`，不属于本笔记主线。


## PyTorch 初学者 API 阅读方法

PyTorch Tensor 与 NumPy 数组很相似，但多了两个深度学习能力：

1. Tensor 可以放到 CPU、MPS 或 CUDA 设备；
2. `requires_grad=True` 时可以记录计算图并自动求导。

看到一个 Tensor 时，优先检查：

```python
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.requires_grad)
```

常见命名规律：

- `torch.zeros(...)`：模块函数；
- `tensor.reshape(...)`：Tensor 方法；
- 末尾带 `_` 的方法通常是原地操作，例如 `zero_()`、`add_()`；
- `tensor.item()`：把单元素 Tensor 转成 Python 标量；
- `tensor.detach()`：返回脱离当前计算图的 Tensor。

与 C++ 类似，shape 不匹配可以理解为函数参数维度不符合接口要求。不要靠试错添加或删除维度，要先写出期望 shape。


In [1]:
import io

import numpy as np
import pandas as pd
import torch

torch.manual_seed(42)

print("PyTorch version:", torch.__version__)


PyTorch version: 2.10.0


## 数学预备知识

如果偏导数、梯度、Jacobian 或多变量链式法则还不熟悉，建议先学习 [`math_foundations_for_ml.ipynb`](math_foundations_for_ml.ipynb)。其中使用二维曲面、等高线和梯度下降路径解释这些概念。


# 第一部分：Tensor 基础

Tensor 是 PyTorch 的核心数据结构。它与 NumPy 数组相似，但还可以：

- 在 CPU、MPS 或 CUDA 等设备上计算；
- 记录计算图并自动求梯度；
- 作为神经网络的输入、参数和中间激活值。


## 1. 基础属性与形状变换（Shapes and Reshape）

- `shape`：每个维度的长度；
- `numel()`：元素总数；
- `reshape()`：改变观察数据的形状，但元素总数必须保持不变。

`reshape` 经常只是改变对内存的“观察方式”；如果内存布局不兼容，PyTorch 也可能创建副本。


In [2]:
# arange 与 NumPy 类似，创建左闭右开的整数序列 [0, 12)。
x = torch.arange(12)          # 生成 0 到 11，共 12 个元素
print("原始形状:", x.shape)   # torch.Size([12])
print("元素总数:", x.numel())

x = x.reshape(3, 4)           # 3 行 4 列，元素总数仍为 12
print("reshape 后:")
print(x)
print("新形状:", x.shape)


原始形状: torch.Size([12])
元素总数: 12
reshape 后:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
新形状: torch.Size([3, 4])


### `reshape`、`view` 与连续内存

`view()` 要求底层内存布局兼容；转置后的 Tensor 通常不连续。`reshape()` 必要时会复制数据，因此使用更稳妥。可以用 `is_contiguous()` 检查。


In [3]:
original = torch.arange(12).reshape(3, 4)
transposed = original.T

print("original 是否连续:", original.is_contiguous())
print("转置后是否连续:", transposed.is_contiguous())
print("安全展平:", transposed.reshape(-1))


original 是否连续: True
转置后是否连续: False
安全展平: tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])


## 2. 算术运算与张量拼接（Operations and Concatenation）

`+ - * / ** exp` 默认是逐元素运算。两个 Tensor 需要形状相同，或者满足广播规则。

`torch.cat` 沿已有维度拼接：

- `dim=0`：增加行数；
- `dim=1`：增加列数。


In [4]:
x_val = torch.tensor([1.0, 2.0, 4.0, 5.0])
y_val = torch.tensor([2.0, 2.0, 2.0, 2.0])

print("逐元素相加:", x_val + y_val)
print("逐元素幂:", x_val ** y_val)
print("指数函数:", torch.exp(x_val))

x_mat = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y_mat = torch.tensor([
    [2.0, 1.0, 4.0, 3.0],
    [1.0, 2.0, 3.0, 4.0],
    [4.0, 3.0, 2.0, 1.0],
])

# cat 沿已有维度拼接；dim=0 增加行，其他维度必须一致。
cat_dim0 = torch.cat((x_mat, y_mat), dim=0)  # (6, 4)
cat_dim1 = torch.cat((x_mat, y_mat), dim=1)  # (3, 8)

print("dim=0:", cat_dim0.shape)
print("dim=1:", cat_dim1.shape)


逐元素相加: tensor([3., 4., 6., 7.])
逐元素幂: tensor([ 1.,  4., 16., 25.])
指数函数: tensor([  2.7183,   7.3891,  54.5982, 148.4132])
dim=0: torch.Size([6, 4])
dim=1: torch.Size([3, 8])


## 3. 广播机制（Broadcasting）

广播从**最右侧维度**开始比较。每对维度必须满足以下条件之一：

1. 两个长度相等；
2. 其中一个长度为 `1`；
3. 某一方缺少该维度，缺少部分视为 `1`。

例如 `(3, 1)` 与 `(1, 2)` 可以共同扩展成 `(3, 2)`。广播通常不会真的复制完整数据，而是以更节省内存的方式完成运算。


In [5]:
a = torch.arange(3).reshape(3, 1)  # 3 行 1 列
b = torch.arange(2).reshape(1, 2)  # 1 行 2 列

# a 的列维度 1 扩展到 2；b 的行维度 1 扩展到 3。
result = a + b
print("a shape:", a.shape)
print("b shape:", b.shape)
print("结果 shape:", result.shape)
print(result)


a shape: torch.Size([3, 1])
b shape: torch.Size([1, 2])
结果 shape: torch.Size([3, 2])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 4. 内存与原地操作（In-place Operations）

`y = y + x` 创建新 Tensor 并让名称 `y` 指向它。`y += x`、`y.add_(x)` 或切片赋值会尽量修改原内存。

原地操作能减少临时内存，但在自动求导中可能破坏反向传播需要保存的中间值。训练模型时不要为了“省内存”随意给参与计算图的 Tensor 使用原地操作。


In [ ]:
x_mat = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y_mat = torch.ones_like(x_mat)

# data_ptr 返回底层数据内存地址，可用于观察是否重新分配。
before_pointer = y_mat.data_ptr()
y_mat = y_mat + x_mat
print("y = y + x 后内存是否相同:", y_mat.data_ptr() == before_pointer)

z = torch.zeros_like(x_mat)
before_pointer = z.data_ptr()
z[:] = x_mat + y_mat
print("切片赋值后内存是否相同:", z.data_ptr() == before_pointer)


y = y + x 后内存是否相同: False
切片赋值后内存是否相同: True


## 5. Tensor、NumPy 与 Python 标量转换

在 CPU 上：

- `tensor.numpy()` 返回的 NumPy 数组通常与 Tensor 共享内存；
- `torch.from_numpy(array)` 通常共享内存；
- `torch.tensor(array)` 会复制数据。

`.item()` 把只含一个元素的 Tensor 转成 Python 标量。


In [ ]:
tensor_cpu = torch.arange(4, dtype=torch.float32)
array_shared = tensor_cpu.numpy()             # 通常共享内存，从pytorch 的 tensor到 numpy
# from_numpy 与 CPU NumPy 数组共享内存；torch.tensor 会复制。
tensor_shared = torch.from_numpy(array_shared) # 通常共享内存，从numpy 到 tensor
tensor_copied = torch.tensor(array_shared)     # 创建副本


array_shared[0] = -99
print("原 Tensor 被共享修改:", tensor_cpu)
print("from_numpy:", tensor_shared)
print("torch.tensor 副本:", tensor_copied)

scalar = torch.tensor([3.5])
print(".item():", scalar.item(), type(scalar.item()))
print("float():", float(scalar))


原 Tensor 被共享修改: tensor([-99.,   1.,   2.,   3.])
from_numpy: tensor([-99.,   1.,   2.,   3.])
torch.tensor 副本: tensor([0., 1., 2., 3.])
.item(): 3.5 <class 'float'>
float(): 3.5


# 第二部分：从表格数据到 Tensor

原始项目数据常来自 CSV。完整流程是：

`读取 → 分离特征和标签 → 填补缺失值 → 编码类别 → 转为 float32 Tensor`

下面把整个流程放在**同一个代码单元**中。这个单元包含自己的 `import` 和原始数据，因此可以单独、重复运行，不依赖前面单元留下的变量。

> 修改其中一步后，请重新运行这整个代码单元。不要只复制最后几行运行，因为后面的变量由前面的步骤产生。


In [1]:
# 这个单元是一个完整程序：只运行这一个单元也可以得到最终 Tensor。
import io

import pandas as pd
import torch

# ---------- 第 1 步：准备并读取 CSV ----------
# 三引号字符串可以跨多行书写，内容采用 CSV 的“逗号分隔”格式。
# CSV 的基本规则：第一行通常是列名；后面每一行是一条样本；同一行数据用逗号分隔。
csv_text = """NumRooms,Alley,Price
NA,Pave,127500
2,NA,106000
4,NA,178100
NA,NA,140000
"""

# StringIO 把字符串包装成“内存中的文本文件”；csv_file 是文件对象，不是路径。
# 这样虽然没有在硬盘上创建 house.csv，但仍然可以交给本来需要“文件”的 read_csv。
csv_file = io.StringIO(csv_text)
# read_csv 读取文件对象，把第一行识别为列名，其余行解析成 DataFrame。
# 默认情况下，CSV 中的 NA 会被识别成缺失值 NaN。
data = pd.read_csv(csv_file)

print("1. 原始 DataFrame")
print(data)
print("列的数据类型:")
print(data.dtypes)

# ---------- 第 2 步：分离输入特征 X 和预测目标 y ----------
# iloc[行位置, 列位置] 按整数位置选择。
# : 表示所有行；0:2 包含第 0、1 列，但不包含第 2 列。
inputs = data.iloc[:, 0:2].copy()  # 多列特征：得到 DataFrame，也就是二维表格。
# 单独选择第 2 列会得到一维 Series；它是模型要预测的 Price。
outputs = data.iloc[:, 2].copy()   # 单列标签：得到 Series，也就是一维序列。

print("\n2. 分离后的特征和标签")
print("inputs shape:", inputs.shape)
print(inputs)
print("outputs shape:", outputs.shape)
print(outputs)

# ---------- 第 3 步：填补数值列的缺失值 ----------
# select_dtypes(include="number") 只保留数值列，再用 .columns 取得列名。
# Alley 是字符串/缺失值混合的类别列，不是数值列，所以这里不会被选中。
numeric_columns = inputs.select_dtypes(include="number").columns
# inputs[numeric_columns] 根据列名取出所有数值列，结果仍是 DataFrame。
numeric_inputs = inputs[numeric_columns]
# mean() 默认分别计算每一列的平均值。本例 NumRooms 的均值是 (2 + 4) / 2 = 3。
column_means = numeric_inputs.mean()
# fillna(column_means) 按列名对齐，用每一列自己的均值替换该列的 NaN。
filled_numeric_inputs = numeric_inputs.fillna(column_means)
# 把填补后的数值列放回 inputs；文本列 Alley 暂时保持不变。
inputs[numeric_columns] = filled_numeric_inputs

print("\n3. 数值缺失值填补后")
print("数值列:", numeric_columns.tolist())
print("每列均值:")
print(column_means)
print(inputs)

# ---------- 第 4 步：把字符串类别编码成数值 ----------
# 神经网络不能直接计算字符串 "Pave"，因此把 Alley 拆成 0/1 指示列。
# dummy 在这里可以理解为“虚拟变量”：用 0/1 数值列表示原来的类别。
encoded_inputs = pd.get_dummies(
    inputs,
    columns=["Alley"],    # 只编码 Alley 列
    dummy_na=True,        # 把缺失值也当成一个类别，生成 Alley_nan
    dtype="float32",     # 生成 0.0/1.0，方便转成模型常用的 float32
)

print("\n4. 独热编码后")
print(encoded_inputs)
# encoded_inputs.columns 是“列名索引对象”，不是函数；不能写成 encoded_inputs.columns()。
# .tolist() 把它转换成普通 Python list，方便查看和调试。
print("特征顺序:", encoded_inputs.columns.tolist())

# ---------- 第 5 步：DataFrame/Series → NumPy → Tensor ----------
# to_numpy 丢掉 Pandas 的列名和行索引，只保留按当前列顺序排列的数值。
x_numpy = encoded_inputs.to_numpy(dtype="float32")
y_numpy = outputs.to_numpy(dtype="float32")
# torch.tensor 根据 NumPy 数据创建新的 Tensor；dtype 再次明确模型使用 float32。
x_table = torch.tensor(x_numpy, dtype=torch.float32)
y_table = torch.tensor(y_numpy, dtype=torch.float32)

print("\n5. 最终 Tensor")
print("输入 Tensor x_table:")
print(x_table)
print("标签 Tensor y_table:", y_table)
print("x_table shape:", x_table.shape, "= 4 个样本 × 3 个特征")
print("y_table shape:", y_table.shape, "= 4 个样本各有 1 个标签")
print("Tensor 数据类型:", x_table.dtype, y_table.dtype)


1. 原始 DataFrame
   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
列的数据类型:
NumRooms    float64
Alley           str
Price         int64
dtype: object

2. 分离后的特征和标签
inputs shape: (4, 2)
   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
outputs shape: (4,)
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

3. 数值缺失值填补后
数值列: ['NumRooms']
每列均值:
NumRooms    3.0
dtype: float64
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

4. 独热编码后
   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0
特征顺序: ['NumRooms', 'Alley_Pave', 'Alley_nan']

5. 最终 Tensor
输入 Tensor x_table:
tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])
标签 Tensor y_table: tensor([127500., 106000

## 文件读写补充：真实 CSV 的读取和写入

上面的 `StringIO` 是为了让示例不修改磁盘。真实项目通常给 `read_csv` 一个文件路径：

```python
from pathlib import Path

# Path 用 / 组合路径，macOS 和 Windows 都可以使用。
csv_path = Path("data") / "house.csv"
print("当前工作目录:", Path.cwd())
print("文件是否存在:", csv_path.exists())

# Pandas 会替我们打开、读取并关闭文件。
data = pd.read_csv(csv_path)

# index=False 表示不要把 DataFrame 左侧的 0、1、2... 行索引写进 CSV。
data.to_csv(csv_path, index=False)
```

- `Path.cwd()`：Notebook 当前从哪个文件夹寻找相对路径；
- `csv_path.exists()`：文件是否真的存在；
- `pd.read_csv(path)`：硬盘上的 CSV → DataFrame；
- `data.to_csv(path, index=False)`：DataFrame → 硬盘上的 CSV。

如果出现 `FileNotFoundError`，通常不是 Pandas 函数坏了，而是当前工作目录与文件路径没有对应上。


## 6. 数据切片与缺失值处理

`data.iloc[行位置, 列位置]` 使用整数位置选择数据：

- `:` 表示所有行；
- `0:2` 遵循 Python 的左闭右开切片，选择第 0、1 列；
- `data.iloc[:, 0:2]` 返回二维 DataFrame，shape 为 `(4, 2)`；
- `data.iloc[:, 2]` 返回一维 Series，shape 为 `(4,)`；
- `.copy()` 创建独立副本，后续修改 `inputs` 时不含糊地影响原始 `data`。

`mean()` 默认分别计算每个数值列的均值，`fillna(...)` 再用对应列的均值填补缺失项。文本列不能计算均值，所以先使用 `select_dtypes(include="number")` 只选择数值列。

> 真实机器学习项目中，均值只能从训练集计算，再用同一个均值处理验证集和测试集，否则会发生数据泄漏。


## 7. 类别特征独热编码（One-hot Encoding）

模型不能直接计算字符串 `"Pave"`。`pd.get_dummies` 把一个类别列拆成多个 0/1 列：

```text
Alley = Pave  →  Alley_Pave = 1, Alley_nan = 0
Alley = NaN   →  Alley_Pave = 0, Alley_nan = 1
```

`columns=["Alley"]` 指定要编码的列；`dummy_na=True` 把缺失本身作为一个类别；`dtype="float32"` 让结果直接适合深度学习计算。


## 8. 转换为 NumPy 与 PyTorch Tensor

`encoded_inputs.to_numpy(dtype="float32")` 把 DataFrame 转成二维 NumPy 数组。转换后，列名和行索引会消失，只剩数值及其排列顺序。因此转换前要检查：

```python
print(encoded_inputs.columns.tolist())
```

`torch.tensor(x_numpy, dtype=torch.float32)` 再根据 NumPy 数组创建 Tensor。最终 `x_table.shape == (4, 3)` 表示 4 个样本、每个样本 3 个特征。


### 修改代码时的安全检查

修改这一节后，直接重新运行上面的完整代码单元，并依次检查：

1. `data.columns` 是否仍包含 `NumRooms`、`Alley`、`Price`；
2. `inputs.isna().sum()` 中数值列是否还有缺失值；
3. `encoded_inputs.dtypes` 是否全部为数值类型；
4. `x_table.shape[0] == y_table.shape[0]`，输入与标签的样本数是否相同；
5. `x_table.dtype` 和 `y_table.dtype` 是否为 `torch.float32`。

如果你增加、删除或改名 CSV 的列，也要同步修改 `iloc` 的选择范围或改用明确的列名，例如 `data[["NumRooms", "Alley"]]`。


### 本节变量地图

| 变量 | 类型 | shape | 含义 |
|---|---|---:|---|
| `data` | DataFrame | `(4, 3)` | 从 CSV 读取的原始表格 |
| `inputs` | DataFrame | `(4, 2)` | 清洗中的输入特征 |
| `outputs` | Series | `(4,)` | 房价标签 |
| `encoded_inputs` | DataFrame | `(4, 3)` | 完成缺失值和类别处理的数值特征 |
| `x_numpy` | ndarray | `(4, 3)` | 去掉列名后的 NumPy 特征数组 |
| `x_table` | Tensor | `(4, 3)` | 模型输入 |
| `y_table` | Tensor | `(4,)` | 模型标签 |


# 第三部分：线性代数基础

深度学习中的全连接层、卷积、注意力和损失函数都建立在线性代数运算上。重点不是背 API，而是理解运算前后的形状。


## 9. 标量、向量、矩阵和多维 Tensor

- 标量：0 阶 Tensor，shape 为 `()`
- 向量：1 阶 Tensor，shape 为 `(n,)`
- 矩阵：2 阶 Tensor，shape 为 `(m, n)`
- 多维 Tensor：例如图像批次常为 `(batch, channels, height, width)`


In [ ]:
a = torch.tensor(3.0)
b = torch.tensor(2.0)
print("标量运算:", a + b, a * b, a / b, a ** b)

vector = torch.arange(4)
print("向量第 4 个元素:", vector[3])
print("向量长度:", len(vector))

A = torch.arange(20).reshape(5, 4)
print("矩阵 A:")
print(A)
print("A 的转置:")
print(A.T)

symmetric = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print("是否对称:", torch.equal(symmetric, symmetric.T))

image_like = torch.arange(24).reshape(2, 3, 4)
print("三阶 Tensor shape:", image_like.shape)


标量运算: tensor(5.) tensor(6.) tensor(1.5000) tensor(9.)
向量第 4 个元素: tensor(3)
向量长度: 4
矩阵 A:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
A 的转置:
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
是否对称: True
三阶 Tensor shape: torch.Size([2, 3, 4])


## 10. 降维、`axis` 与 `keepdims`

对形状为 `(3, 4)` 的矩阵：

- `sum(axis=0)` 消除第 0 维，结果形状为 `(4,)`；
- `sum(axis=1)` 消除第 1 维，结果形状为 `(3,)`；
- `keepdims=True` 不让该维度消失，而是把长度变成 `1`。

设

$$
A=
\begin{bmatrix}
1&2&3&4\\
5&5&5&5\\
1&2&3&4
\end{bmatrix}.
$$

沿 `axis=1` 求和：

- `keepdims=False` → `[10, 20, 10]`，shape `(3,)`
- `keepdims=True` → 列向量，shape `(3, 1)`

`keepdims=True` 的主要价值是让结果继续保留“每一行一个统计量”的二维含义，并能自然广播回原矩阵。例如每行除以自己的行和：

$$
A \div \operatorname{sum}(A,\ axis=1,\ keepdims=True).
$$

可记忆为：**axis 指定要被压缩的维度，keepdims 决定它是消失还是缩成 1。**


In [ ]:
A_demo = torch.tensor([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 5.0, 5.0, 5.0],
    [1.0, 2.0, 3.0, 4.0],
])

sum_without_keepdims = A_demo.sum(axis=1, keepdims=False)
sum_with_keepdims = A_demo.sum(axis=1, keepdims=True)

print("keepdims=False:", sum_without_keepdims,
      sum_without_keepdims.shape)
print("keepdims=True:")
print(sum_with_keepdims, sum_with_keepdims.shape)
print("每行除以该行之和:")
print(A_demo / sum_with_keepdims)


keepdims=False: tensor([10., 20., 10.]) torch.Size([3])
keepdims=True:
tensor([[10.],
        [20.],
        [10.]]) torch.Size([3, 1])
每行除以该行之和:
tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.1000, 0.2000, 0.3000, 0.4000]])


## 11. 点积、矩阵乘法与形状

- `torch.dot(x, y)`：两个向量的点积，结果是标量；
- `torch.mv(A, x)`：矩阵—向量积；
- `torch.mm(A, B)`：矩阵—矩阵积；
- `A @ B`：更通用、也更常用的矩阵乘法写法。


In [ ]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
B = torch.ones(4, 3)

# dot: (n,)·(n,) -> scalar；mv: (m,n)@(n,) -> (m,)。
print("点积:", torch.dot(x, y))             # scalar
print("矩阵-向量:", torch.mv(A, x).shape)   # (5,)
print("矩阵-矩阵:", torch.mm(A, B).shape)   # (5, 3)
print("@ 的结果与 mm 相同:",
      torch.equal(A @ B, torch.mm(A, B)))




点积: tensor(6.)
矩阵-向量: torch.Size([5])
矩阵-矩阵: torch.Size([5, 3])
@ 的结果与 mm 相同: True


## 12. 范数（Norms）

范数衡量向量或矩阵的“大小”：

- L2 范数：$\sqrt{\sum_i x_i^2}$，即欧氏长度；
- L1 范数：$\sum_i |x_i|$；
- Frobenius 范数：矩阵所有元素平方和再开根号。

正则化、梯度裁剪和距离计算都经常使用范数。


In [15]:
u = torch.tensor([3.0, -4.0])
print("L2 范数:", torch.norm(u))             # 5
print("L1 范数:", torch.abs(u).sum())        # 7
print("4×9 全 1 矩阵的 Frobenius 范数:",
      torch.norm(torch.ones((4, 9))))       # sqrt(36) = 6


L2 范数: tensor(5.)
L1 范数: tensor(7.)
4×9 全 1 矩阵的 Frobenius 范数: tensor(6.)


# 第四部分：自动求导（Automatic Differentiation）

自动求导既不是符号求导（Symbolic Differentiation），也不是用微小差分近似导数的数值求导（Numerical Differentiation）。它把程序拆成基础操作，并使用链式法则精确组合局部导数。

## 13. 计算图（Computational Graph）

计算图把数学表达式表示为有向无环图（DAG）：

- **节点**：输入、中间变量、输出或常数；
- **边 / 操作**：`+`、`×`、`exp`、`log` 等数据依赖。

对

$$
f(x_1,x_2)=\ln(x_1)+x_1x_2
$$

可拆为：

1. $v_1=\ln(x_1)$
2. $v_2=x_1x_2$
3. $v_3=v_1+v_2$

PyTorch 在执行这些操作时动态构建计算图。


## 14. 链式法则（Chain Rule）

对复合函数 $y=f(g(h(x)))$：

$$
\frac{dy}{dx}
=
\frac{dy}{dg}
\cdot
\frac{dg}{dh}
\cdot
\frac{dh}{dx}.
$$

在计算图中，如果从某个变量到输出存在多条路径，全导数需要把各条路径的贡献相加。反向传播就是高效重复使用这些局部导数。


### 多条路径的梯度为什么要相加？

假设同一个输入 $x$ 通过两条路径影响输出：

$$
u=x^2,\qquad v=3x,\qquad y=u+v.
$$

$x$ 对 $y$ 的总影响是两条路径贡献之和：

$$
\frac{dy}{dx}
=
\frac{\partial y}{\partial u}\frac{du}{dx}
+
\frac{\partial y}{\partial v}\frac{dv}{dx}
=1\cdot2x+1\cdot3
=2x+3.
$$

神经网络中一个参数可能通过许多后续节点影响损失。反向传播在分叉处把梯度分发，在汇合处把来自不同路径的梯度相加。


In [ ]:
x_branch = torch.tensor(2.0, requires_grad=True)#requires_grad=True 意思是：我要让 PyTorch 追踪这个变量参与的计算，之后对它求导。
u_branch = x_branch ** 2
v_branch = 3 * x_branch
y_branch = u_branch + v_branch
y_branch.backward()

print("自动求导:", x_branch.grad.item())#.item() 是把只有一个数的 tensor 转成普通 Python 数字。
print("理论结果 2x+3:", (2 * x_branch + 3).item())


自动求导: 7.0
理论结果 2x+3: 7.0


## 15. 正向模式与反向模式

### 正向模式（Forward-mode AD）

- 计算函数值的同时，维护每个变量对某个输入的导数；
- 方向与前向计算一致；
- 内存开销较低；
- 若输入很多，需要针对不同输入重复计算；
- 适合输入维度远小于输出维度的情况。

### 反向模式（Reverse-mode AD）

1. 前向过程计算并保存中间值；
2. 从标量输出开始，反向计算输出对各中间变量的导数。

深度学习通常有百万级参数，但损失是一个标量，因此一次反向传播就能得到所有参数梯度。

| 特性 | 正向模式 | 反向模式 |
|---|---|---|
| 主要乘积 | Jacobian-vector product (JVP) | vector-Jacobian product (VJP) |
| 计算量主要取决于 | 输入维度 | 输出维度 |
| 内存 | 较低 | 较高，需要保存中间激活 |
| 典型应用 | 科学计算、几何分析 | 深度学习反向传播 |


### Jacobian 与 VJP 的 shape

若函数 $\mathbf f:\mathbb R^n\to\mathbb R^m$，完整 Jacobian 的 shape 是 `(m, n)`。当 $m,n$ 很大时，直接构造它代价很高。

反向传播从后面接收一个长度为 $m$ 的上游梯度 $\mathbf v$，计算 vector-Jacobian product：

$$
\mathbf v^T J.
$$

结果长度为 $n$，正好对应函数输入的梯度。PyTorch 的非标量 `backward(gradient=...)` 就是在指定这个上游向量。


神经网络里的维度通常非常大。

假设某一层是：

f:R
1000000
→R
1000000

那么完整 Jacobian 的 shape 是：

(1000000, 1000000)

也就是 10
12
 个数。

这太大了，根本不现实。

但反向传播真正需要的不是整个 Jacobian，而是：
$$
\mathbf v^T J.
$$
也就是：

已经知道后面对输出的梯度 v，现在只需要算它传回输入后是什么。

所以 PyTorch 通常不会显式构造完整 Jacobian，而是直接算 VJP。

In [ ]:
def vector_function(inputs: torch.Tensor) -> torch.Tensor:
    x, y = inputs
    return torch.stack((x ** 2 + y, x * y))


point = torch.tensor([2.0, 3.0], requires_grad=True)
jacobian = torch.autograd.functional.jacobian(vector_function, point)#计算某个函数的jacobian矩阵
#注意第一个输入的是vector_function 而不是vector_function(point),因为 PyTorch 需要知道：这个函数长什么样，然后自己把 point 代进去，并自动求导。
print("Jacobian:")
print(jacobian)
print("shape:", jacobian.shape)  # (输出维度 2, 输入维度 2)

upstream = torch.tensor([1.0, 0.5])#loss对输出的梯度，因为backward只能处理数字，给他一个矩阵无法处理
expected_vjp = upstream @ jacobian
print("上游梯度 @ Jacobian:", expected_vjp)


Jacobian:
tensor([[4., 1.],
        [3., 2.]])
shape: torch.Size([2, 2])
上游梯度 @ Jacobian: tensor([5.5000, 2.0000])


## 16. `requires_grad` 与第一次反向传播

若

$$
y=2\mathbf{x}^T\mathbf{x}=2\sum_i x_i^2,
$$

则

$$

rac{\partial y}{\partial \mathbf{x}}=4\mathbf{x}.
$$

`requires_grad=True` 告诉 PyTorch 记录与该 Tensor 相关的运算。标量 `y` 可以直接调用 `backward()`。


In [ ]:
# requires_grad=True 让 PyTorch 记录 x 之后参与的运算。
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)

print("y:", y)             # 2 * (0² + 1² + 2² + 3²) = 28
y.backward()

print("自动求导结果:", x.grad)
print("理论结果 4x:", 4 * x.detach())#detach() 的意思是：把一个 Tensor 从自动求导计算图里“摘出来”，和 x 的数值一样，但 PyTorch 不再追踪它后续参与的运算。
print("是否一致:", torch.equal(x.grad, 4 * x.detach()))


y: tensor(28., grad_fn=<MulBackward0>)
自动求导结果: tensor([ 0.,  4.,  8., 12.])
理论结果 4x: tensor([ 0.,  4.,  8., 12.])
是否一致: True


## 17. 梯度累加机制

PyTorch 默认把新梯度**累加**到 `.grad`，而不是覆盖。这样可以支持梯度累积等训练策略；普通训练中，每次反向传播前通常要清零。


In [ ]:
# x.grad 目前是 [0, 4, 8, 12]。
y = x.sum()
y.backward()  # dy/dx = [1, 1, 1, 1]，会加到旧梯度上
print("未清零，梯度发生累加:", x.grad)

x.grad.zero_()#梯度清零操作
y = x.sum()
y.backward()
print("清零后重新计算:", x.grad)


未清零，梯度发生累加: tensor([ 1.,  5.,  9., 13.])
清零后重新计算: tensor([1., 1., 1., 1.])


## 18. `detach()`：把值当作常数

`detach()` 返回数值相同、但不再连接当前计算图的 Tensor。反向传播经过它时，不会继续追踪它原来的计算过程。


In [ ]:
x.grad.zero_()
y = x * x
# detach 保留数值但切断求导关系，u 会被当作常数。
u = y.detach()  # u 的值为 x²，但求导时把 u 当常数
z = u * x

z.sum().backward()
print("z=u*x, 且 u 为常数，所以 dz/dx=u:")
print(x.grad)
print("是否等于 u:", torch.equal(x.grad, u))

# y 本身仍保留 y=x² 的计算关系。
x.grad.zero_()
y.sum().backward()
print("dy/dx=2x:", x.grad)


z=u*x，且 u 为常数，所以 dz/dx=u:
tensor([0., 1., 4., 9.])
是否等于 u: True
dy/dx=2x: tensor([0., 2., 4., 6.])


## 19. 动态计算图与 Python 控制流

PyTorch 记录的是本次运行真正经过的路径，因此函数里可以使用 `if`、`while` 等普通 Python 控制流。


In [21]:
def f(a: torch.Tensor) -> torch.Tensor:
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c


a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

# 对本次实际路径而言，f(a)=k*a，所以 df/da=k=f(a)/a。
print("a:", a.item(), "f(a):", d.item())
print("自动求导:", a.grad.item())
print("理论验证:", (d / a).item())
print("是否接近:", torch.allclose(a.grad, d / a))


a: 0.33669036626815796 f(a): 1379.083740234375
自动求导: 4096.0
理论验证: 4096.0
是否接近: True


## 本笔记学完后应能回答

- Tensor 的 `shape`、`dtype` 和 `device` 分别表示什么？
- `reshape`、广播和 `axis` 会怎样改变 shape？
- 为什么 `keepdims=True` 更方便做归一化？
- 点积、矩阵—向量积和矩阵—矩阵积的输入输出 shape 是什么？
- `requires_grad=True` 后，PyTorch 记录了什么？
- 为什么连续两次 `backward()` 会累加梯度？
- `detach()` 为什么会阻断一条求导路径？
- Python 的 `if` 和 `while` 为什么仍能参与动态计算图？

能用自己的语言解释这些问题后，再进入可选训练扩展。
