In [4]:
import numpy as np

# 1. NumPy 数组的基础属性
# np.array() 将 Python 列表转换为 NumPy 数组
array = np.array([[1, 2, 3],
                  [1, 2, 3]])

print("=== 1. NumPy 数组的基础属性 ===")
print("原始矩阵:\n", array)

# ndim: 维度数（数组的秩），即有几层嵌套
print("维度 (ndim):", array.ndim) 
# shape: 形状，返回一个元组，表示 (行数, 列数)
print("形状 (shape):", array.shape)
# size: 元素总个数，即 行 * 列
print("元素个数 (size):", array.size)

In [27]:
import numpy as np

print("\n=== 2. 数据类型 (dtype) ===")
# 默认根据输入数据推断类型
a = np.array([2, 23, 4])
print("默认类型数组:", a, " 类型:", a.dtype)

# 手动指定为整数类型 (int)
a_int = np.array([2, 23, 4], dtype=int)
print("指定 int 类型:", a_int, " 类型:", a_int.dtype)

# 手动指定为浮点数类型 (float)
a_float = np.array([2, 23, 4], dtype=float)
print("指定 float 类型:", a_float, " 类型:", a_float.dtype)

In [ ]:
import numpy as np

print("\n=== 3. 特殊数组的创建 ===")
a_manual = np.array([[1, 3, 6], [2, 8, 4]])
print("手动创建矩阵:\n", a_manual)

# np.zeros: 创建全 0 矩阵 (3行4列)
a_zeros = np.zeros((3, 4))
print("全 0 矩阵 (zeros):\n", a_zeros)

# np.ones: 创建全 1 矩阵 (5行4列)
a_ones = np.ones((5, 4), dtype=int)
print("全 1 矩阵 (ones):\n", a_ones)

# np.empty: 创建“空”矩阵，其值是内存中原有的数据（接近 0）
a_empty = np.empty((3, 4))
print("未初始化矩阵 (empty):\n", a_empty)

In [26]:
import numpy as np

print("\n=== 4. 序列生成与形状变换 ===")
# np.arange: 生成等差序列 (起始, 终点, 步长) -> 左闭右开
a_range = np.arange(10, 20, 2)
print("等差序列 (10到20, 步长2):", a_range)

# reshape: 重新调整数组的维度
a_reshape = np.arange(12).reshape((3, 4))
print("0-11 重构为 3x4 矩阵:\n", a_reshape)

# np.linspace: 生成线段序列 (起始, 终点, 元素个数)
a_lin = np.linspace(1, 10, 5)
print("线段序列 (1到10, 取5个点):", a_lin)

a_lin_reshape = np.linspace(1, 10, 6).reshape((2, 3))
print("线段序列重构为 2x3 矩阵:\n", a_lin_reshape)

In [17]:
import numpy as np

print("\n=== 5. 基础数学运算 ===")
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print("数组 a:", a, " 数组 b:", b)

# 对应位置相减
print("减法 (a - b):", a - b)
# 对应位置相加
print("加法 (a + b):", a + b)
# 乘方运算 (双星号)
print("平方 (b**2):", b**2)
# 三角函数运算 (作用于每个元素)
print("三角函数 (10 * sin(a)):", 10 * np.sin(a))

# 逻辑判断 (返回布尔数组)
print("判断 b < 3:", b < 3)
print("判断 b == 3:", b == 3)

print("\n--- 矩阵乘法对比 ---")
a_mat = np.array([[1, 1], [0, 1]])
b_mat = np.arange(4).reshape((2, 2))
print("矩阵 A:\n", a_mat)
print("矩阵 B:\n", b_mat)

# 逐位乘法 (*): 相同位置的数字直接相乘
c_mul = a_mat * b_mat
print("逐位乘法 (A * B):\n", c_mul)

# 矩阵乘法 (dot): 线性代数中的矩阵积运算
c_dot = np.dot(a_mat, b_mat)
c_dot_2 = a_mat.dot(b_mat) # 等效写法
print("矩阵积 (np.dot(A, B)):\n", c_dot)

In [ ]:
import numpy as np

print("\n=== 6. 统计运算与轴 (axis) ===")
a = np.random.random((2, 4))
print("原始随机矩阵:\n", a)

print("总和 (sum):", np.sum(a))
print("最大值 (max):", np.max(a))
print("最小值 (min):", np.min(a))

# axis=0 表示对“列”操作（垂直方向）
print("每列最小值 (axis=0):", np.min(a, axis=0))
# axis=1 表示对“行”操作（水平方向）
print("每行最小值 (axis=1):", np.min(a, axis=1))
print("每列总和 (axis=0):", np.sum(a, axis=0))

In [ ]:
import numpy as np

print("\n=== 7. 进阶统计、排序与转置 ===")
A = np.arange(14, 2, -1).reshape((3, 4))
print("操作矩阵 A:\n", A)

print("最小值的索引 (argmin):", np.argmin(A))
print("最大值的索引 (argmax):", np.argmax(A))
print("平均值 (mean):", np.mean(A))
print("中位数 (median):", np.median(A))

# 累计求和 (cumsum): 展示数值演变过程
print("累计求和 (cumsum):", np.cumsum(A))
# 差分运算 (diff): 相邻元素的差值
print("相邻元素差分 (diff):\n", np.diff(A))
# 查找非零元素索引
print("非零元素索引 (nonzero):", np.nonzero(A))
# 逐行排序
print("逐行排序 (sort):\n", np.sort(A))

print("--- 矩阵转置 ---")
print("转置 (transpose):\n", np.transpose(A))
print("转置简写 (A.T):\n", A.T)

print("--- 数值截断 ---")
# 将 A 中小于 5 的数改为 5，大于 9 的数改为 9
print("数值截断 (clip, 范围5到9):\n", np.clip(A, 5, 9))

In [ ]:
import numpy as np

print("\n=== 8. 索引、切片与迭代 ===")
A = np.arange(3, 15).reshape((3, 4))
print("操作矩阵 A:\n", A)

print("A[2]: 获取第 3 行:", A[2])
print("A[1, 1]: 获取第 2 行第 2 列:", A[1, 1])
print("A[2, :]: 获取第 3 行所有数:", A[2, :])
print("A[:, 1]: 获取第 2 列所有数:", A[:, 1])
print("A[1, 1:3]: 获取第 2 行中索引 1 到 2 的数:", A[1, 1:3])

print("--- 迭代操作 ---")
print("按行迭代:")
for row in A:
    print("  ", row)

print("按列迭代 (通过转置实现):")
for column in A.T:
    print("  ", column)

print("扁平化迭代 (迭代每一个元素):")
print("  扁平化数组:", A.flatten())
print("  前 5 个元素:", end=" ")
for count, item in enumerate(A.flat):
    if count < 5: print(item, end=" ")
print("...")

In [1]:
import numpy as np

print("\n=== 9. 矩阵合并与维度增加 ===")
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
print("数组 A:", A, " 数组 B:", B)

# vstack: 垂直合并 (Vertical stack)
print("垂直合并 (vstack):\n", np.vstack((A, B)))

# hstack: 水平合并 (Horizontal stack)
print("水平合并 (hstack):", np.hstack((A, B)))

print("--- 维度操作 ---")
# np.newaxis: 在指定位置增加一个新维度
print("增加行维度 A[np.newaxis, :]:", A[np.newaxis, :], " 形状:", A[np.newaxis, :].shape)
print("增加列维度 A[:, np.newaxis]:\n", A[:, np.newaxis], " 形状:", A[:, np.newaxis].shape)

A_col = A[:, np.newaxis]
B_col = B[:, np.newaxis]
print("左右合并 (hstack 两个列向量):\n", np.hstack((A_col, B_col)))

# concatenate: 指定轴进行合并 (axis=0 为垂直, axis=1 为水平)
res_cat = np.concatenate((A_col, B_col, B_col, A_col), axis=1)
print("使用 concatenate (axis=1) 合并 4 个列向量:\n", res_cat)


=== 9. 矩阵合并与维度增加 ===
数组 A: [1 1 1]  数组 B: [2 2 2]
垂直合并 (vstack):
 [[1 1 1]
 [2 2 2]]
水平合并 (hstack): [1 1 1 2 2 2]
--- 维度操作 ---
增加行维度 A[np.newaxis, :]: [[1 1 1]]  形状: (1, 3)
增加列维度 A[:, np.newaxis]:
 [[1]
 [1]
 [1]]  形状: (3, 1)
左右合并 (hstack 两个列向量):
 [[1 2]
 [1 2]
 [1 2]]
使用 concatenate (axis=1) 合并 4 个列向量:
 [[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
