In [4]:
import numpy as np
#1.matrix
array = np.array([[1,2,3],
                  [1,2,3]])
print(array)
print("number of dim:", array.ndim) #dimension of the array 不是线性代数里的维数，是数组的维数（几行）
print("shape:", array.shape)
print("size:",array.size)

[[1 2 3]
 [1 2 3]]
number of dim: 2
shape: (2, 3)
size: 6


In [27]:
import numpy as np

a = np.array([2,23,4])
print(a)
print(a.dtype)

a = np.array([2,23,4],dtype=int)# the type of the elements in the matrix
print(a)
print(a.dtype)

a = np.array([2,23,4],dtype=float)
print(a)
print(a.dtype)

[ 2 23  4]
int64
[ 2 23  4]
int64
[ 2. 23.  4.]
float64


In [ ]:
import numpy as np

a = np.array([[1,3,6],
             [2,8,4]])
print(a)

a = np.zeros((3,4))#3行4列的全是0的矩阵
print(a)

a = np.ones((5,4),dtype=int)
print(a)

a=np.empty((3,4))#a number close to 0
print(a)

[[1 3 6]
 [2 8 4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
import numpy as np

a = np.arange(10,20,2)#左闭右开 （起始，最终，公差）
print(a)

a=np.arange(12).reshape((3,4))#从0开始数12个数，形状由reshape控制几行几列
print(a)

a = np.linspace(1,10,5)#生成一个线段 （起始，终点，有几个数）
print(a)
a = np.linspace(1,10,6).reshape((2,3))
print(a)

[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [17]:
import numpy as np

a = np.array([10,20,30,40])
b = np.arange(4)

print(a,b)
print("-----")
c=a-b
print(c)
print("-----")
c=a+b
print(c)
print("-----")
c=b**2 #平方是双星号
print(c)
print("-----")

c = 10*np.sin(a)#对a的每个值，求sin再乘10
print(c)
print("-----")

print(b)
print(b<3)#b里面哪些值小于3
print(b==3)
print("---------")
print("矩阵乘法：")
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape((2,2))
print("a==",a)
print("b==",b)
print('-------')
c = a*b#同行同列的数字相乘 
c_dot=np.dot(a,b) #矩阵运算中的乘法
c_dot_2 = a.dot(b)#和c_dot等价
print(c)
print(c_dot)
print(c_dot_2)

[10 20 30 40] [0 1 2 3]
-----
[10 19 28 37]
-----
[10 21 32 43]
-----
[0 1 4 9]
-----
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
-----
[0 1 2 3]
[ True  True  True False]
[False False False  True]
---------
矩阵乘法：
a== [[1 1]
 [0 1]]
b== [[0 1]
 [2 3]]
-------
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [ ]:
import numpy as np

a = np.random.random((2,4))#生成一个2行4列的随机的矩阵
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))

print(np.min(a,axis = 0))#在每一列中寻找最小值
print(np.min(a,axis = 1))#在每一行中寻找最小值
print(np.sum(a,axis=0))

[[0.99461659 0.78243689 0.21747656 0.85757454]
 [0.89058374 0.59628944 0.14281228 0.48297073]]
4.964760776982405
0.9946165858204001
0.142812283208124
[0.89058374 0.59628944 0.14281228 0.48297073]
[0.21747656 0.14281228]
[1.88520033 1.37872634 0.36028884 1.34054527]


In [ ]:
import numpy as np

A = np.arange(14,2,-1).reshape((3,4))
print(A)

print(np.argmin(A))# 最小值的索引（位置）
print(np.argmax(A))# 最大值的索引
print(A.mean())# get average of the matrix
print(np.mean(A))# the same as the one above
print(np.average(A)) # same
print(np.median(A))#中位数
print(np.cumsum(A))#把第i个数之前的（包含自己）都加起来
print(np.diff(A))#第i+1个数和第i个数的差
print(np.nonzero(A))#输出A中非0值的行数（记载在第一个array里）和列数（第二个array里面）
print(np.sort(A))#按照逐行进行排序

print(np.transpose(A))#转置
print(A.T)#转置的另一种写法
print((A.T).dot(A))

print(np.clip(A,5,9))#让A里面所有小于5的数都等于5，大于9的都等于9

print(np.mean(A,axis=0))#对列计算
print(np.mean(A,axis=1))#对行计算


[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
11
0
8.5
8.5
8.5
8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
[10.  9.  8.  7.]


In [ ]:
import numpy as np

A = np.arange(3,15)
print(A)
print(A[3])#A中索引为3的
A= np.arange(3,15).reshape((3,4))
print(A)
print(A[2])#索引为2 的行（第三行）
print(A[1][1])#第一行第一列（从0开始数）
print(A[1,1])#和上一个一样
print(A[2,:])#第二行的所有数
print(A[:,1])
print(A[1,1:3])#第一行，第一个到第三个（左闭右开）
print("-------")
for row in A:#打印每一行 (这样的循环都默认是循环每一行)
    print(row)
print("-------")
for column in A.T:#没法直接循环每一行，但是可以用转置来
    print(column)
print("-------")
print(A.flatten())#把A变为一行，返回变完之后的数组
for item in A.flat:#A.flat 相当于一个迭代器
    print(item)






[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[11 12 13 14]
[ 4  8 12]
[8 9]
-------
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
-------
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
-------
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [ ]:
import numpy as np

A =np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))# vertical stack 上下合并

C = np.vstack((A,B))
print(A.shape,C.shape)

D = np.hstack((A,B))# horizontal stack 左右合并
print(D)
print(A.shape,D.shape)

print(A.T)#不能用transpose把一个序列变成一个矩阵
print(A.T.shape)

print(A[np.newaxis,:])#给A在行的层次上加了一个维度
print(A[:,np.newaxis])#给A在列的层次上加了一个维度
A =np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A)
print(B)
D = np.hstack((A,B))# horizontal stack 左右合并
print(D)
print(A.shape,D.shape)


C = np.concatenate((A,B,B,A),axis = 0)#进行多个矩阵的合并,在列的方向（上下）合并
print(C)


[[1 1 1]
 [2 2 2]]
(3,) (2, 3)
[1 1 1 2 2 2]
(3,) (6,)
[1 1 1]
(3,)
[[1 1 1]]
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
